### ISSUE TITLE
Adapt Observe queries

### ISSUE THREAD

**Issue by JulienLebranchu** [OB7-IRD/fishi#11]
We have a complete set of queries to extract data from balbaya but with the new workflow, I need the same extraction from Observe.

Goals : Extract the data from Observe 
 - Need to check and adapt the set of queries on observe.

List of indicators :

- [ ] Vessel number
- [ ] Vessel capacity
- [ ] Time at sea and fishing time
- [ ] number of total set, FAD set, FSC set, positive set by school type
- [ ] FAD deployement 
- [ ] Set time in days

**Comment by ClaraLerebourg** [comment]
List of updated indicators : fishery production, fishing activity, fishing time, spatial occupancy, map catch distribution and fishing capacity.

_Indicators that cannot be achieved because one of the data elements (set_duration) is not present in observe as it is an output of t3: set per searching day, catch per searching day, catch per unit effort, map effort distribution and fishing effort_
